# Generated by Django 4.2.6 on 2023-11-19 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_type", models.CharField(max_length=255, null=True)),
                ("device_ip", models.CharField(max_length=255, null=True)),
                ("device_name", models.CharField(max_length=255, null=True)),
                ("extra", models.JSONField(null=True)),
                ("is_on", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Relay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relay_pin", models.IntegerField()),
                ("is_on", models.BooleanField(default=False)),
                ("relay_name", models.CharField(max_length=255, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="device.device"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RelayGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=255, unique=True)),
                ("is_on", models.BooleanField(default=True)),
                ("relays", models.ManyToManyField(to="device.relay")),
            ],
        ),
        migrations.CreateModel(
            name="RelayRelayGroupAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_on", models.BooleanField(default=True)),
                (
                    "relay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="device.relay"
                    ),
                ),
                (
                    "relay_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relay_group_associations",
                        to="device.relaygroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="relay",
            name="relay_group_associations",
            field=models.ManyToManyField(
                related_name="relay_group_associations",
                to="device.relayrelaygroupassociation",
            ),
        ),
        migrations.AddField(
            model_name="relay",
            name="relay_groups",
            field=models.ManyToManyField(to="device.relaygroup"),
        ),
    ]
