# Generated by Django 4.2.6 on 2023-11-21 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relay",
            name="device",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="device.device",
            ),
        ),
        migrations.AlterField(
            model_name="relay",
            name="relay_group_associations",
            field=models.ManyToManyField(
                null=True,
                related_name="relay_group_associations",
                to="device.relayrelaygroupassociation",
            ),
        ),
        migrations.AlterField(
            model_name="relay",
            name="relay_groups",
            field=models.ManyToManyField(null=True, to="device.relaygroup"),
        ),
        migrations.AlterField(
            model_name="relaygroup",
            name="relays",
            field=models.ManyToManyField(null=True, to="device.relay"),
        ),
        migrations.AlterField(
            model_name="relayrelaygroupassociation",
            name="relay",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="device.relay",
            ),
        ),
        migrations.AlterField(
            model_name="relayrelaygroupassociation",
            name="relay_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relay_group_associations",
                to="device.relaygroup",
            ),
        ),
    ]
