# Generated by Django 4.2.6 on 2023-11-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "device",
            "0004_device_created_at_device_updated_at_relay_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="relayschedule",
            name="is_on",
            field=models.BooleanField(default=True),
        ),
    ]
