# Generated by Django 4.2.6 on 2024-05-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0005_relayschedule_is_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "if_when",
                    models.CharField(
                        choices=[("If", "If"), ("When", "When")], max_length=50
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("Schedule", "Schedule"),
                            ("Relay State Change", "Relay State Change"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("On", "On"),
                            ("Off", "Off"),
                            ("Toggle", "Toggle"),
                            ("Dim", "Dim"),
                            ("Lockout", "Lockout"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[("Group", "Group"), ("Relay", "Relay")], max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
